required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 8
  y: 125
  z: 8
  yaw: 180
  pitch: 0
areas:
  0:
    world: 'world'
    spawns:
      red:
        x: 62
        y: 65
        z: 8
        yaw: 180
        pitch: 0
      blue:
        x: 8
        y: 65
        z: -45
        yaw: -90
        pitch: 0
      green:
        x: -45
        y: 65
        z: 8
        yaw: 0
        pitch: 0
      yellow:
        x: 8
        y: 65
        z: 62
        yaw: 90
        pitch: 0