name: nwusBedwars
version: '1.0-SNAPSHOT'
main: org.example.test.nwusBedwars.NwusBedwars
api-version: '1.21'
commands:
  bw:
    usage: /bw
    description: Commands for BedWars
permissions:
  bw.create:
    default: op
    description: Create new arena
  bw.join:
    default: true
    description: Join arena
  bw.delete:
    default: op
    description: Delete arena
  bw.list:
    default: true
    description: List of arenas
  bw.getItem:
    default: op
    description: Get custom item(iron, gold, diamond or emerald)